### PR TITLE
SOSSE-8416 Delete gemfile.lock file

### PR DESCRIPTION
**Pull request by VicZhang1**
Hi,

I delete the `Gemfile.lock` file and ignore it for future. Please help to review, thanks.

Thanks,
-
Vic

### CODE REVIEW

**Comment by ejhinde** [comment]
Looks ok to me. Maybe I am not the best judge.

**Comment by VicZhang1** [comment]
Thanks, updated.

**Comment by VicZhang1** [comment]
I tested the changes, we can still build successfully.

**Comment by chuchuva** [comment]
@VicZhang1 Deleting gemfile.lock is not going to help. You still have ffi and jekyll dependencies that have vulnerabilities.

You should update them to versions that have identified vulnerabilities fixed.

See https://www.linkedin.com/learning/programming-foundations-secure-coding/dependency-issues?u=2290258

**Pull request merged**
